#!/usr/bin/env python3
"""
PublicForward/ForVPS/vps_server.py — Enhanced VPS Bridge (FastAPI + WebSocket).

Exposes an OpenAI-compatible REST API (/v1/chat/completions, /v1/models) and
bridges requests over WebSocket to one or more local workers (public.py),
each of which drives a pool of real DeepSeek browsers.

NEW FEATURES:
  1. CORS middleware
  2. Worker ID generated by VPS (not from worker)
  3. Worker wait timeout (queue requests with timeout)
  4. update_accounts from worker (runtime account updates)
  5. /v1/models show live accounts from workers
  6. X-Session-ID response header
  7. X-Account-Name + X-Conversation-URL headers
  8. think_mode field (DeepSeek alias)
  9. Attachment with "filename"+"data"+"mime_type"
  10. finish_reason + tool_calls response path (OpenAI-compatible)
  11. x_meta block in response (session, account, timing, conversation_url)
  12. Worker stats detail in /health and /
  13. reject_future() when worker sends error message

Run:
  python vps_server.py --port 8000 --token MY_SHARED_SECRET
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import time
import uuid
from contextlib import asynccontextmanager
from typing import Any, AsyncGenerator, Optional

from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.responses import JSONResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import uvicorn


# =========================================================================== #
# Config (env / CLI)
# =========================================================================== #
AUTH_TOKEN = os.environ.get("PAF_TOKEN", "change-me")
REQUEST_TIMEOUT = float(os.environ.get("PAF_REQUEST_TIMEOUT", "330"))
WORKER_WAIT_TIMEOUT = float(os.environ.get("WORKER_WAIT_TIMEOUT", "60"))

# Feature 8: think_mode aliases (DeepSeek-specific)
THINK_MODE_ALIASES = {
    "auto": {"model_tab": "instant", "deep_think": False, "web_search": False},
    "instant": {"model_tab": "instant", "deep_think": False, "web_search": False},
    "thinking": {"model_tab": "expert", "deep_think": True, "web_search": False},
    "expert": {"model_tab": "expert", "deep_think": True, "web_search": False},
    "reasoning": {"model_tab": "expert", "deep_think": True, "web_search": False},
    "fast": {"model_tab": "instant", "deep_think": False, "web_search": False},
    "vision": {"model_tab": "vision", "deep_think": False, "web_search": False},
}

MODEL_ALIASES = {
    # OpenAI-style model id -> (model_tab, deep_think)
    "deepseek-chat": {"model_tab": "instant", "deep_think": False},
    "deepseek-reasoner": {"model_tab": "expert", "deep_think": True},
    "deepseek-vision": {"model_tab": "vision", "deep_think": False},
}

# =========================================================================== #
# Model → backend routing (unified gateway)
# =========================================================================== #
# The `model` field in the request body selects the backend. Session continuity
# is driven exclusively by the X-Session-ID header (see chat_completions).
DEEPSEEK_MODELS = {
    "deepseek", "deepseek-chat", "deepseek-reasoner",
    "deepseek-vision", "deepseek-coder",
}
QWEN_MODELS = {
    "qwen", "qwen-turbo", "qwen-plus", "qwen-max",
}


def resolve_backend(model: str) -> str:
    """Map a request `model` string to a backend id ('deepseek' | 'qwen')."""
    m = (model or "").lower().strip()
    if m in DEEPSEEK_MODELS or m.startswith("deepseek"):
        return "deepseek"
    if m in QWEN_MODELS or m.startswith("qwen"):
        return "qwen"
    raise HTTPException(
        status_code=400,
        detail=(
            f"Unknown model: {model!r}. Use 'deepseek' or 'qwen' "
            "(or their aliases like deepseek-chat, qwen-max)."
        ),
    )


# =========================================================================== #
# Pydantic models — OpenAI Chat Completions schema
# =========================================================================== #
class ChatMessage(BaseModel):
    role: str
    content: Any = None  # str, list of content parts, or None (for tool_calls)
    name: Optional[str] = None
    # Tool calling support (parity with PAF-ModelQwen):
    tool_calls: Optional[list] = None    # set when role=assistant & has tool_call
    tool_call_id: Optional[str] = None   # set when role=tool (tool result)


class ToolFunctionDef(BaseModel):
    name: str
    description: Optional[str] = None
    parameters: Optional[dict] = None


class Tool(BaseModel):
    type: str = "function"
    function: ToolFunctionDef


class AttachmentPayload(BaseModel):
    """Feature 9: Enhanced attachment with filename + data + mime_type."""

    filename: str
    data: str  # base64-encoded
    mime_type: str


class ChatCompletionRequest(BaseModel):
    model: str = "deepseek-chat"
    messages: list[ChatMessage]
    stream: bool = False
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    tools: Optional[list[Tool]] = None
    # Custom DeepSeek extensions:
    deep_think: Optional[bool] = None
    web_search: Optional[bool] = None
    model_tab: Optional[str] = None
    session_id: Optional[str] = None
    mode: Optional[str] = None  # "new" | "continue"
    attachments: Optional[list[AttachmentPayload]] = None
    # think_mode: DeepSeek alias (resolved to model_tab/deep_think/web_search)
    # OR Qwen think mode ("auto"|"thinking"|"fast") — passed through as-is.
    think_mode: Optional[str] = None
    # Feature 4: preferred_account routing (DeepSeek account name / Qwen cookie file)
    preferred_account: Optional[str] = None
    # Qwen-specific: task_type ("chat" | "create_image" | "create_video" | "web_search")
    task_type: Optional[str] = None
    # Tool choice (Qwen forwards this; DeepSeek ignores it)
    tool_choice: Optional[str] = "auto"

    def last_user_message(self) -> str:
        for msg in reversed(self.messages):
            if msg.role == "user":
                if isinstance(msg.content, str):
                    return msg.content
                if isinstance(msg.content, list):
                    parts = [
                        p.get("text", "")
                        for p in msg.content
                        if isinstance(p, dict) and p.get("type") == "text"
                    ]
                    return "\n".join(parts)
        return ""


# Rebuild models
for _m in (ChatMessage, ToolFunctionDef, Tool, AttachmentPayload, ChatCompletionRequest):
    _m.model_rebuild()


# =========================================================================== #
# Helpers
# =========================================================================== #
def _token_estimate(text: str) -> int:
    if not text:
        return 0
    return max(1, len(text) // 4)


def _make_id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:24]}"


def _resolve_think_mode(req: ChatCompletionRequest) -> dict:
    """Feature 8: Resolve think_mode to DeepSeek parameters."""
    if req.think_mode:
        alias = THINK_MODE_ALIASES.get(req.think_mode.lower())
        if alias:
            return alias
    return {}


# =========================================================================== #
# WorkerManager
# =========================================================================== #
class WorkerEntry:
    def __init__(
        self, worker_id: str, ws: WebSocket, max_concurrent: int,
        accounts: list, backend: str = "deepseek"
    ) -> None:
        self.worker_id = worker_id
        self.ws = ws
        self.max_concurrent = max_concurrent
        self.accounts = accounts
        self.backend = backend        # ← "deepseek" | "qwen" (model routing)
        self.in_flight = 0
        self.connected_at = time.time()
        self.last_ping = time.time()


class WorkerManager:
    def __init__(self) -> None:
        self.workers: dict[str, WorkerEntry] = {}
        self._futures: dict[str, asyncio.Future] = {}
        self._session_worker: dict[str, str] = {}
        self._rr_index = 0
        self._lock = asyncio.Lock()
        self._worker_counter = 0

    # ----- Feature 2: VPS-generated worker IDs ------------------------ #
    def _generate_worker_id(self, hostname: str) -> str:
        """Generate unique worker ID on VPS side."""
        self._worker_counter += 1
        return f"worker-{hostname}-{self._worker_counter:03d}"

    # ----- registration ---------------------------------------------- #
    async def register(
        self, ws: WebSocket, hostname: str, max_concurrent: int,
        accounts: list, backend: str = "deepseek"
    ) -> str:
        worker_id = self._generate_worker_id(hostname)
        async with self._lock:
            self.workers[worker_id] = WorkerEntry(
                worker_id, ws, max_concurrent, accounts, backend
            )
        print(f"[vps] worker registered: {worker_id} backend={backend} accounts={accounts}")
        return worker_id

    async def unregister(self, worker_id: str) -> None:
        async with self._lock:
            self.workers.pop(worker_id, None)
            # Clean up session affinity
            to_remove = [k for k, v in self._session_worker.items() if v == worker_id]
            for k in to_remove:
                self._session_worker.pop(k, None)
        print(f"[vps] worker unregistered: {worker_id}")

    # ----- Feature 4: update_accounts runtime ------------------------ #
    async def update_accounts(self, worker_id: str, accounts: list[str]) -> None:
        """Update account list for a worker at runtime."""
        async with self._lock:
            if worker_id in self.workers:
                self.workers[worker_id].accounts = accounts
                print(f"[vps] updated accounts for {worker_id}: {accounts}")

    @staticmethod
    def _account_matches(account: Any, name: str) -> bool:
        """Match a preferred-account name against a worker account entry.

        DeepSeek accounts are plain strings; Qwen accounts are dicts
        ({"account"|"cookie_file"|"name": ...}). Handle both.
        """
        if isinstance(account, str):
            return account == name
        if isinstance(account, dict):
            return name in (
                account.get("account"),
                account.get("cookie_file"),
                account.get("name"),
            )
        return False

    # ----- Feature 3: Worker wait timeout (backend-aware) ------------ #
    async def dispatch(
        self,
        backend: str,
        task_fields: dict,
        mode: str = "new",
        session_id: Optional[str] = None,
        preferred_account: Optional[str] = None,
    ) -> dict:
        """Dispatch a task to a worker of the given *backend*."""
        # Session affinity for continue mode — the browser lives on one worker.
        if mode == "continue" and session_id and session_id in self._session_worker:
            worker_id = self._session_worker[session_id]
            if worker_id in self.workers and self.workers[worker_id].backend == backend:
                return await self._dispatch_to_worker(
                    worker_id, backend, task_fields, session_id
                )

        # Wait for an available worker (of this backend) with timeout.
        start_wait = time.time()
        while time.time() - start_wait < WORKER_WAIT_TIMEOUT:
            worker_id = await self._pick_worker(backend, preferred_account)
            if worker_id:
                if session_id:
                    self._session_worker[session_id] = worker_id
                return await self._dispatch_to_worker(
                    worker_id, backend, task_fields, session_id
                )
            await asyncio.sleep(0.5)

        raise TimeoutError(f"No available '{backend}' worker within timeout")

    async def _pick_worker(
        self, backend: str, preferred_account: Optional[str] = None
    ) -> Optional[str]:
        """Pick least-loaded worker of *backend*, optionally filtering by account."""
        async with self._lock:
            candidates = [
                w
                for w in self.workers.values()
                if w.backend == backend
                and w.in_flight < w.max_concurrent
                and (
                    not preferred_account
                    or any(self._account_matches(a, preferred_account) for a in w.accounts)
                )
            ]
            if not candidates:
                return None
            # Round-robin among candidates
            self._rr_index = (self._rr_index + 1) % len(candidates)
            return candidates[self._rr_index].worker_id

    async def _dispatch_to_worker(
        self,
        worker_id: str,
        backend: str,
        task_fields: dict,
        session_id: Optional[str],
    ) -> dict:
        worker = self.workers.get(worker_id)
        if not worker:
            raise RuntimeError(f"Worker {worker_id} not found")

        task_id = f"task-{uuid.uuid4().hex[:12]}"
        future: asyncio.Future = asyncio.Future()
        self._futures[task_id] = future

        worker.in_flight += 1

        try:
            if backend == "qwen":
                # Qwen worker protocol: {"type":"task","request_id","payload"}
                envelope = {
                    "type": "task",
                    "request_id": task_id,
                    "payload": task_fields,
                }
            else:
                # DeepSeek worker protocol: {"type":"task","task_id","request"}
                envelope = {
                    "type": "task",
                    "task_id": task_id,
                    "request": task_fields,
                }
            await worker.ws.send_json(envelope)
            result = await asyncio.wait_for(future, timeout=REQUEST_TIMEOUT)
            return result
        finally:
            worker.in_flight -= 1
            self._futures.pop(task_id, None)

    # ----- result handling (both worker protocols) ------------------- #
    async def handle_result(self, msg: dict) -> None:
        # DeepSeek worker: {"type":"result","task_id","result":{...}}
        # Qwen worker:     {"type":"result","request_id","data":{...}}
        task_id = msg.get("task_id") or msg.get("request_id")
        payload = msg.get("result")
        if payload is None:
            payload = msg.get("data", {})
        if task_id in self._futures:
            self._futures[task_id].set_result(payload or {})

    # ----- Feature 13: reject_future on error ------------------------ #
    async def handle_error(self, msg: dict) -> None:
        """Immediately reject future when worker sends error (both protocols)."""
        task_id = msg.get("task_id") or msg.get("request_id")
        if task_id in self._futures:
            # DeepSeek uses "error"; Qwen uses "message".
            error_msg = msg.get("error") or msg.get("message") or "Worker error"
            status = msg.get("status", 500)
            # Create HTTPException to propagate status
            exc = HTTPException(status_code=status, detail=error_msg)
            self._futures[task_id].set_exception(exc)

    # ----- Feature 12: Worker stats ---------------------------------- #
    def get_stats(self) -> dict:
        """Get detailed worker statistics."""
        return {
            "total_workers": len(self.workers),
            "workers": [
                {
                    "worker_id": w.worker_id,
                    "backend": w.backend,
                    "accounts": w.accounts,
                    "max_concurrent": w.max_concurrent,
                    "in_flight": w.in_flight,
                    "connected_at": w.connected_at,
                    "uptime_seconds": time.time() - w.connected_at,
                }
                for w in self.workers.values()
            ],
            "total_accounts": sum(len(w.accounts) for w in self.workers.values()),
            "busy_slots": sum(w.in_flight for w in self.workers.values()),
        }

    @staticmethod
    def _account_id(account: Any) -> str:
        """Normalise an account entry (str or dict) to a display id."""
        if isinstance(account, str):
            return account
        if isinstance(account, dict):
            return str(
                account.get("account")
                or account.get("cookie_file")
                or account.get("name")
                or account
            )
        return str(account)

    # ----- Feature 5: List all available accounts (with backend) ----- #
    def list_all_accounts(self) -> list[dict]:
        """List all accounts across all workers, tagged with their backend."""
        seen: set[tuple[str, str]] = set()
        out: list[dict] = []
        for w in self.workers.values():
            for a in w.accounts:
                aid = self._account_id(a)
                key = (aid, w.backend)
                if key in seen:
                    continue
                seen.add(key)
                out.append({"id": aid, "backend": w.backend})
        out.sort(key=lambda d: (d["backend"], d["id"]))
        return out


# =========================================================================== #
# FastAPI app
# =========================================================================== #
worker_mgr = WorkerManager()


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield


app = FastAPI(
    title="PAF-ModelDeepSeek Enhanced VPS Bridge",
    description="OpenAI-compatible API for DeepSeek with session persistence & account routing",
    version="2.0.0",
    lifespan=lifespan,
)

# Feature 1: CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure as needed for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =========================================================================== #
# WebSocket endpoint (worker connection)
# =========================================================================== #
@app.websocket("/ws/worker")
async def worker_endpoint(ws: WebSocket):
    await ws.accept()
    worker_id: Optional[str] = None
    try:
        # Registration
        msg = await ws.receive_json()
        if msg.get("type") != "register":
            await ws.close(code=4000, reason="Expected register message")
            return

        # Token may arrive in the register body (DeepSeek worker) OR as a
        # ws query param ?token=... (Qwen worker). Enforce only when the
        # operator configured a real token (not the "change-me" default).
        token = msg.get("token") or ws.query_params.get("token", "")
        if AUTH_TOKEN and AUTH_TOKEN != "change-me" and token != AUTH_TOKEN:
            await ws.close(code=4001, reason="Invalid token")
            return

        hostname = msg.get("hostname", "unknown")
        max_concurrent = msg.get("max_concurrent", 1)
        accounts = msg.get("accounts", [])
        # Backend for model routing. Default "deepseek" for legacy workers that
        # predate the unified gateway; the Qwen worker sends "qwen".
        backend = (msg.get("backend") or "deepseek").lower()

        worker_id = await worker_mgr.register(
            ws, hostname, max_concurrent, accounts, backend
        )
        await ws.send_json({"type": "registered", "worker_id": worker_id})

        # Message loop
        async for raw in ws.iter_json():
            mtype = raw.get("type")
            if mtype == "result":
                await worker_mgr.handle_result(raw)
            elif mtype == "error":
                await worker_mgr.handle_error(raw)
            elif mtype == "update_accounts":
                await worker_mgr.update_accounts(worker_id, raw.get("accounts", []))
            elif mtype == "ping":
                # Update last_ping timestamp
                if worker_id in worker_mgr.workers:
                    worker_mgr.workers[worker_id].last_ping = time.time()
                await ws.send_json({"type": "pong"})
            elif mtype == "pong":
                if worker_id in worker_mgr.workers:
                    worker_mgr.workers[worker_id].last_ping = time.time()

    except WebSocketDisconnect:
        pass
    except Exception as e:
        print(f"[vps] worker error: {e}")
    finally:
        if worker_id:
            await worker_mgr.unregister(worker_id)


# =========================================================================== #
# REST API endpoints
# =========================================================================== #
@app.get("/")
async def root():
    """Feature 12: Show detailed worker stats on root."""
    stats = worker_mgr.get_stats()
    return {
        "service": "PAF-ModelDeepSeek Enhanced VPS Bridge",
        "version": "2.0.0",
        "status": "running",
        "workers": stats,
    }


@app.get("/health")
async def health():
    """Feature 12: Detailed health check with worker stats."""
    stats = worker_mgr.get_stats()
    return {
        "status": "healthy" if stats["total_workers"] > 0 else "no_workers",
        "workers": stats,
        "timestamp": time.time(),
    }


@app.get("/v1/models")
async def list_models():
    """List models: the two backend ids plus live per-account entries."""
    # Which backends currently have at least one worker connected.
    live_backends = sorted({w.backend for w in worker_mgr.workers.values()})
    data = [
        {"id": b, "object": "model", "owned_by": "PAF-ai", "x_backend": b}
        for b in live_backends
    ]
    # Per-account entries (each tagged with its backend).
    for acc in worker_mgr.list_all_accounts():
        data.append(
            {
                "id": acc["id"],
                "object": "model",
                "owned_by": "PAF-ai",
                "x_backend": acc["backend"],
            }
        )
    return {"object": "list", "data": data}


@app.post("/v1/chat/completions")
async def chat_completions(request: Request, req: ChatCompletionRequest):
    """Unified chat completions — routes to DeepSeek or Qwen by `model`.

    Session continuity is driven by the X-Session-ID header (standard for both
    backends). The legacy body field `mode` is ignored.
    """
    start_time = time.time()

    try:
        backend = resolve_backend(req.model)

        # ── Session: X-Session-ID header is the standard (body session_id is
        #    accepted as a fallback for old clients). mode is derived purely
        #    from whether a session id is present; body "mode" is ignored. ──
        session_id = (
            request.headers.get("X-Session-ID", "").strip()
            or (req.session_id or "").strip()
            or None
        )
        mode = "continue" if session_id else "new"
        if not session_id:
            session_id = f"sess-{uuid.uuid4().hex[:16]}"

        # ── Common payload pieces (both backends) ──
        attachments = None
        if req.attachments:
            attachments = [
                {"filename": a.filename, "data": a.data, "mime_type": a.mime_type}
                for a in req.attachments
            ]
        tools_payload = [t.model_dump() for t in req.tools] if req.tools else None
        messages_payload = [m.model_dump(exclude_none=True) for m in req.messages]

        # Kept for x_meta (DeepSeek only)
        model_tab = deep_think = web_search = None

        if backend == "deepseek":
            # think_mode alias → (model_tab, deep_think, web_search)
            think_mode_params = _resolve_think_mode(req)
            model_tab = req.model_tab or think_mode_params.get("model_tab")
            deep_think = (
                req.deep_think if req.deep_think is not None
                else think_mode_params.get("deep_think", False)
            )
            web_search = (
                req.web_search if req.web_search is not None
                else think_mode_params.get("web_search", False)
            )
            if not model_tab:
                alias = MODEL_ALIASES.get(req.model)
                if alias:
                    model_tab = alias["model_tab"]
                    if req.deep_think is None:
                        deep_think = alias["deep_think"]
            model_tab = model_tab or "instant"

            system_prompt = "\n\n".join(
                m.content for m in req.messages
                if m.role == "system" and isinstance(m.content, str) and m.content.strip()
            ) or None
            tool_messages = [
                {
                    "role":         m.role,
                    "tool_call_id": m.tool_call_id,
                    "name":         m.name,
                    "content":      m.content if isinstance(m.content, str)
                                    else json.dumps(m.content, ensure_ascii=False),
                }
                for m in req.messages if m.role == "tool"
            ] or None

            task_fields = {
                "prompt": req.last_user_message(),
                "mode": mode,
                "session_id": session_id,
                "preferred_account": req.preferred_account,
                "model_tab": model_tab,
                "deep_think": deep_think,
                "web_search": web_search,
                "attachments": attachments,
                "tools": tools_payload,
                "max_tokens": req.max_tokens,
                "system_prompt": system_prompt,
                "tool_messages": tool_messages,
                "messages": messages_payload,
            }
        else:  # backend == "qwen"
            # think_mode passed through as-is; the Qwen worker derives its own
            # prompt/mode from messages + its session store.
            task_fields = {
                "messages": messages_payload,
                "model": req.model,
                "stream": req.stream,
                "think_mode": req.think_mode,
                "session_id": session_id,
                "max_tokens": req.max_tokens,
                "task_type": req.task_type or "chat",
                "tools": tools_payload,
                "tool_choice": req.tool_choice if req.tools else None,
                "attachments": attachments or [],
                "preferred_cookie": req.preferred_account,
            }

        # ── Dispatch to a worker of the resolved backend ──
        result = await worker_mgr.dispatch(
            backend=backend,
            task_fields=task_fields,
            mode=mode,
            session_id=session_id,
            preferred_account=req.preferred_account,
        )

        # ── Normalise the two worker result shapes into one ──
        if backend == "qwen":
            if not result.get("success"):
                raise HTTPException(
                    status_code=502,
                    detail=result.get("error", "Qwen worker error"),
                )
            response_text = result.get("response", "")
            worker_usage = result.get("usage") or {}
            tool_calls = (
                result.get("tool_calls")
                if result.get("finish_reason") == "tool_calls" else None
            )
            account_id = result.get("cookie_file")
            conversation_url = result.get("conversation_url")
            actual_mode = mode
            mode_fallback = False
        else:  # deepseek
            if not result.get("ok"):
                raise HTTPException(
                    status_code=500,
                    detail=result.get("error", "DeepSeek worker error"),
                )
            response_text = result.get("text", "")
            worker_usage = result.get("usage") or {}
            tool_calls = result.get("tool_calls")
            account_id = result.get("account")
            conversation_url = result.get("conversation_url")
            actual_mode = result.get("mode", mode)
            mode_fallback = result.get("mode_fallback", False)

        # Token usage (prefer worker's accurate count, fall back to estimate).
        prompt_tokens = worker_usage.get("prompt_tokens")
        completion_tokens = worker_usage.get("completion_tokens")
        if prompt_tokens is None:
            prompt_tokens = _token_estimate(req.last_user_message())
        if completion_tokens is None:
            completion_tokens = _token_estimate(response_text)
        total_tokens = worker_usage.get(
            "total_tokens", prompt_tokens + completion_tokens
        )

        finish_reason = "tool_calls" if tool_calls else "stop"
        choice = {
            "index": 0,
            "message": {
                "role": "assistant",
                # OpenAI spec: content must be null when returning tool_calls.
                "content": None if tool_calls else response_text,
            },
            "finish_reason": finish_reason,
        }
        if tool_calls:
            choice["message"]["tool_calls"] = tool_calls

        x_meta = {
            "session_id": session_id,
            "backend": backend,               # ← model routing surfaced to client
            "mode": actual_mode,
            "mode_fallback": mode_fallback,
            "account": account_id,
            "conversation_url": conversation_url,
            "response_time": time.time() - start_time,
            "timestamp": time.time(),
        }
        if backend == "deepseek":
            x_meta["model_tab"] = model_tab
            x_meta["deep_think"] = deep_think
            x_meta["web_search"] = web_search

        # Fold worker-supplied x_metadata without clobbering VPS-set keys.
        for _k, _v in (result.get("x_metadata") or {}).items():
            x_meta.setdefault(_k, _v)

        response_data = {
            "id": _make_id(),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": req.model,
            "choices": [choice],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": total_tokens,
            },
            "x_meta": x_meta,
        }

        headers = {
            "X-Session-ID": session_id,
            "X-Backend": backend,
        }
        if account_id:
            headers["X-Account-Name"] = str(account_id)
        if conversation_url:
            headers["X-Conversation-URL"] = str(conversation_url)

        return JSONResponse(content=response_data, headers=headers)

    except HTTPException:
        raise
    except TimeoutError as e:
        raise HTTPException(status_code=504, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# =========================================================================== #
# Main
# =========================================================================== #
def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="PAF-ModelDeepSeek Enhanced VPS Server")
    p.add_argument("--port", type=int, default=8000, help="Port to listen on")
    p.add_argument("--host", default="0.0.0.0", help="Host to bind to")
    p.add_argument("--token", help="Auth token (overrides PAF_TOKEN env)")
    return p.parse_args()


def main():
    args = _parse_args()
    if args.token:
        global AUTH_TOKEN
        AUTH_TOKEN = args.token

    print(f"[vps] Starting Enhanced VPS Bridge on {args.host}:{args.port}")
    print(f"[vps] Auth token: {AUTH_TOKEN[:8]}***")

    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level="info",
        access_log=True,
    )


if __name__ == "__main__":
    main()
